# This is a basic workflow to help you get started with Actions

name: Test App

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  Test_funcion_sumar:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v4

      # Runs a single command using the runners shell
      - name: Run a one-line script
        run: echo Hello, world!

      # Runs a set of commands using the runners shell
      - name: Run a multi-line script
        run: |
          echo Add other actions to build,
          echo test, and deploy your project.
  Test_funcion_restar:
   
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: nombre_2 step one
        run: ls -l
        
  Test_funcion_multiplicar:
   
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: nombre_2 step one
        run: ls -l

  Test_funcion_dividir:
   
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: nombre_2 step one
        run: ls -l
